// Javascript/16-react/crud/frontend/src/components/home/Home.jsx
import React from 'react'
import Main from '../template/Main'

export default props => 
<   Main icon='home' title='Início' subtitle='Segundo projeto de React' >
        <div className="display-4">Bem Vindo!</div>
        <hr/>
        <p className="mb-0">Sistema para exemplificar a construção de um cadastro desenvolvido em React</p>
    </Main>

// Javascript/19-Angular/frontend/src/app/views/home/home.component.ts
import { Component, OnInit } from '@angular/core';
import { HeaderService } from '../../components/template/header/header.service'

@Component({
  selector: 'app-home',
  templateUrl: './home.component.html',
  styleUrls: ['./home.component.css']
})
export class HomeComponent implements OnInit {

  constructor(private headerService: HeaderService) {
    headerService.headerData = {
      title : 'Início',
      icon: 'home',
      routeUrl: ''

    }
   }

  ngOnInit(): void {
  }

}

<mat-card class="mat-elevation-z3">
    <mat-card-title class="title">
        Bem Vindo!
    </mat-card-title>
    <mat-card-subtitle class="subtitle">
        Sistema para simplificar a contrução de um cadastro em Angular
    </mat-card-subtitle>
</mat-card>
